/**
 * @file maxGraphShapes.ts
 * @brief Built-in maxGraph shapes configuration
 *
 * Complete catalog of maxGraph shape types available for the toolbox
 */

import type { ToolboxItem } from '../components/Toolbox';

/**
 * All built-in maxGraph shapes organized by category
 */
export const MAX_GRAPH_SHAPES: Record<string, ToolboxItem[]> = {
  General: [
    {
      id: 'rectangle',
      name: 'Rectangle',
      type: 'custom',
      group: 'General',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Basic rectangle shape',
    },
    {
      id: 'rounded_rectangle',
      name: 'Rounded Rectangle',
      type: 'custom',
      group: 'General',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Rectangle with rounded corners',
    },
    {
      id: 'circle',
      name: 'Circle',
      type: 'custom',
      group: 'General',
      width: 80,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Circle/ellipse shape',
    },
    {
      id: 'ellipse',
      name: 'Ellipse',
      type: 'custom',
      group: 'General',
      width: 120,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Oval/ellipse shape',
    },
    {
      id: 'diamond',
      name: 'Diamond',
      type: 'custom',
      group: 'General',
      width: 80,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Diamond/rhombus shape',
    },
    {
      id: 'triangle',
      name: 'Triangle',
      type: 'custom',
      group: 'General',
      width: 80,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Triangle shape',
    },
    {
      id: 'hexagon',
      name: 'Hexagon',
      type: 'custom',
      group: 'General',
      width: 100,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Hexagon shape',
    },
    {
      id: 'pentagon',
      name: 'Pentagon',
      type: 'custom',
      group: 'General',
      width: 80,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Pentagon shape',
    },
    {
      id: 'star',
      name: 'Star',
      type: 'custom',
      group: 'General',
      width: 80,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Star shape',
    },
    {
      id: 'parallelogram',
      name: 'Parallelogram',
      type: 'custom',
      group: 'General',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Parallelogram shape',
    },
  ],

  Flowchart: [
    {
      id: 'process',
      name: 'Process',
      type: 'custom',
      group: 'Flowchart',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Process box',
    },
    {
      id: 'decision',
      name: 'Decision',
      type: 'custom',
      group: 'Flowchart',
      width: 80,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Diamond decision node',
    },
    {
      id: 'terminator',
      name: 'Terminator',
      type: 'custom',
      group: 'Flowchart',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Start/End terminator',
    },
    {
      id: 'data',
      name: 'Data',
      type: 'custom',
      group: 'Flowchart',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Data input/output',
    },
    {
      id: 'document',
      name: 'Document',
      type: 'custom',
      group: 'Flowchart',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Document symbol',
    },
    {
      id: 'database',
      name: 'Database',
      type: 'custom',
      group: 'Flowchart',
      width: 80,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Database cylinder',
    },
    {
      id: 'storage',
      name: 'Storage',
      type: 'custom',
      group: 'Flowchart',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Storage symbol',
    },
    {
      id: 'connector',
      name: 'Connector',
      type: 'custom',
      group: 'Flowchart',
      width: 60,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Connection circle',
    },
  ],

  Arrows: [
    {
      id: 'arrow_right',
      name: 'Arrow Right',
      type: 'custom',
      group: 'Arrows',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Right pointing arrow',
    },
    {
      id: 'arrow_left',
      name: 'Arrow Left',
      type: 'custom',
      group: 'Arrows',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Left pointing arrow',
    },
    {
      id: 'arrow_up',
      name: 'Arrow Up',
      type: 'custom',
      group: 'Arrows',
      width: 60,
      height: 100,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Up pointing arrow',
    },
    {
      id: 'arrow_down',
      name: 'Arrow Down',
      type: 'custom',
      group: 'Arrows',
      width: 60,
      height: 100,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Down pointing arrow',
    },
    {
      id: 'arrow_double',
      name: 'Double Arrow',
      type: 'custom',
      group: 'Arrows',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Bidirectional arrow',
    },
    {
      id: 'callout',
      name: 'Callout',
      type: 'custom',
      group: 'Arrows',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Speech bubble callout',
    },
  ],

  UML: [
    {
      id: 'actor',
      name: 'Actor',
      type: 'custom',
      group: 'UML',
      width: 40,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'UML actor stick figure',
    },
    {
      id: 'usecase',
      name: 'Use Case',
      type: 'custom',
      group: 'UML',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'UML use case ellipse',
    },
    {
      id: 'component',
      name: 'Component',
      type: 'custom',
      group: 'UML',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'UML component box',
    },
    {
      id: 'class',
      name: 'Class',
      type: 'custom',
      group: 'UML',
      width: 120,
      height: 100,
      dimensionality: '2D',
      shapeElements: [],
      description: 'UML class box with sections',
    },
    {
      id: 'interface',
      name: 'Interface',
      type: 'custom',
      group: 'UML',
      width: 100,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'UML interface symbol',
    },
    {
      id: 'package',
      name: 'Package',
      type: 'custom',
      group: 'UML',
      width: 120,
      height: 100,
      dimensionality: '2D',
      shapeElements: [],
      description: 'UML package folder',
    },
    {
      id: 'state',
      name: 'State',
      type: 'custom',
      group: 'UML',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'UML state machine state',
    },
  ],

  Connectors: [
    {
      id: 'straight_edge',
      name: 'Straight Connector',
      type: 'custom',
      group: 'Connectors',
      width: 100,
      height: 100,
      dimensionality: '1D',
      shapeElements: [],
      description: 'Straight line connector',
    },
    {
      id: 'curved_edge',
      name: 'Curved Connector',
      type: 'custom',
      group: 'Connectors',
      width: 100,
      height: 100,
      dimensionality: '1D',
      shapeElements: [],
      description: 'Smooth curved connector',
    },
    {
      id: 'orthogonal_edge',
      name: 'Orthogonal Connector',
      type: 'custom',
      group: 'Connectors',
      width: 100,
      height: 100,
      dimensionality: '1D',
      shapeElements: [],
      description: 'Right-angle orthogonal routing',
    },
    {
      id: 'loop_edge',
      name: 'Loop Connector',
      type: 'custom',
      group: 'Connectors',
      width: 100,
      height: 100,
      dimensionality: '1D',
      shapeElements: [],
      description: 'Self-loop connector',
    },
  ],

  Advanced: [
    {
      id: 'rectangle_3d',
      name: '3D Box',
      type: 'custom',
      group: 'Advanced',
      width: 120,
      height: 100,
      dimensionality: '2D',
      shapeElements: [],
      description: '3D perspective box',
    },
    {
      id: 'cylinder',
      name: 'Cylinder',
      type: 'custom',
      group: 'Advanced',
      width: 80,
      height: 100,
      dimensionality: '2D',
      shapeElements: [],
      description: '3D cylinder shape',
    },
    {
      id: 'cone',
      name: 'Cone',
      type: 'custom',
      group: 'Advanced',
      width: 80,
      height: 100,
      dimensionality: '2D',
      shapeElements: [],
      description: '3D cone shape',
    },
    {
      id: 'line',
      name: 'Line',
      type: 'custom',
      group: 'Advanced',
      width: 100,
      height: 1,
      dimensionality: '1D',
      shapeElements: [],
      description: 'Horizontal line',
    },
    {
      id: 'text',
      name: 'Text',
      type: 'custom',
      group: 'Advanced',
      width: 80,
      height: 30,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Text box for labels',
    },
    {
      id: 'label',
      name: 'Label',
      type: 'custom',
      group: 'Advanced',
      width: 60,
      height: 20,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Small label text',
    },
    {
      id: 'group',
      name: 'Group/Container',
      type: 'custom',
      group: 'Advanced',
      width: 200,
      height: 150,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Container for grouping shapes',
    },
  ],

  Networks: [
    {
      id: 'router',
      name: 'Router',
      type: 'custom',
      group: 'Networks',
      width: 80,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Network router node',
    },
    {
      id: 'server',
      name: 'Server',
      type: 'custom',
      group: 'Networks',
      width: 80,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Server computer',
    },
    {
      id: 'client',
      name: 'Client',
      type: 'custom',
      group: 'Networks',
      width: 80,
      height: 80,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Client computer',
    },
    {
      id: 'cloud',
      name: 'Cloud',
      type: 'custom',
      group: 'Networks',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Cloud network',
    },
    {
      id: 'network_device',
      name: 'Network Device',
      type: 'custom',
      group: 'Networks',
      width: 60,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Generic network device',
    },
  ],

  Misc: [
    {
      id: 'image_placeholder',
      name: 'Image',
      type: 'custom',
      group: 'Misc',
      width: 100,
      height: 100,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Image/media placeholder',
    },
    {
      id: 'rectangle_dashed',
      name: 'Dashed Rectangle',
      type: 'custom',
      group: 'Misc',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Rectangle with dashed border',
    },
    {
      id: 'note',
      name: 'Sticky Note',
      type: 'custom',
      group: 'Misc',
      width: 100,
      height: 100,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Sticky note with fold corner',
    },
    {
      id: 'rectangle_rounded_dashed',
      name: 'Rounded Dashed Box',
      type: 'custom',
      group: 'Misc',
      width: 100,
      height: 60,
      dimensionality: '2D',
      shapeElements: [],
      description: 'Rounded rectangle with dashed border',
    },
  ],
};

/**
 * Get all shapes flattened into a single array
 */
export function getAllMaxGraphShapes(): ToolboxItem[] {
  return Object.values(MAX_GRAPH_SHAPES).flat();
}

/**
 * Get shapes by category
 */
export function getShapesByCategory(category: string): ToolboxItem[] {
  return MAX_GRAPH_SHAPES[category] || [];
}

/**
 * Get all available categories
 */
export function getShapeCategories(): string[] {
  return Object.keys(MAX_GRAPH_SHAPES);
}

/**
 * Find shape by ID
 */
export function findShapeById(id: string): ToolboxItem | undefined {
  return getAllMaxGraphShapes().find(shape => shape.id === id);
}

/**
 * Get style string for maxGraph shape
 */
export function getMaxGraphShapeStyle(shapeId: string): string {
  const styles: Record<string, string> = {
    rectangle: 'rounded=0;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    rounded_rectangle: 'rounded=1;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    circle: 'ellipse=1;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    ellipse: 'ellipse=1;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    diamond: 'rhombus=1;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    triangle: 'triangle=1;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    hexagon: 'hexagon=1;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    pentagon: 'polygon=1;points=[[0.5,0],[1,0.4],[0.8,1],[0.2,1],[0,0.4]];strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    star: 'polygon=1;points=[[0.5,0],[0.61,0.35],[1,0.35],[0.68,0.57],[0.79,0.91],[0.5,0.7],[0.21,0.91],[0.32,0.57],[0,0.35],[0.39,0.35]];strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    parallelogram: 'rounded=0;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    decision: 'rhombus=1;strokeColor=#999;fillColor=#fff9e6;strokeWidth=1',
    database: 'ellipse=1;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    document: 'rounded=0;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    cloud: 'cloud=1;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    cylinder: 'cylinder=1;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1',
    note: 'rectangle=1;rounded=0;strokeColor=#999;fillColor=#ffffcc;strokeWidth=1',
  };

  return styles[shapeId] || 'rounded=0;strokeColor=#999;fillColor=#f0f0f0;strokeWidth=1';
}

/**
 * Get all shapes with their maxGraph styles
 */
export function getAllShapesWithStyles(): Array<ToolboxItem & { style: string }> {
  return getAllMaxGraphShapes().map(shape => ({
    ...shape,
    style: getMaxGraphShapeStyle(shape.id),
  }));
}
