export const railwaySVGIcons = {
  rail: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="2" y1="12" x2="22" y2="12"/><circle cx="6" cy="12" r="2"/><circle cx="18" cy="12" r="2"/></svg>`,
  signal: `<svg viewBox="0 0 24 24" fill="currentColor"><rect x="10" y="2" width="4" height="6" fill="currentColor"/><circle cx="12" cy="13" r="3" fill="currentColor"/><circle cx="12" cy="21" r="2" fill="currentColor"/></svg>`,
  switch: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M 2 12 L 10 12 L 18 6"/><path d="M 18 18 L 10 12 L 2 12"/></svg>`,
  junction: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M 2 12 L 22 12"/><path d="M 12 2 L 12 22"/></svg>`,
  platform: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="8" width="20" height="8" fill="currentColor" opacity="0.3"/><line x1="2" y1="12" x2="22" y2="12"/></svg>`,
  station: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18"/><line x1="3" y1="12" x2="21" y2="12"/></svg>`,
  crossing: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="2" y1="2" x2="22" y2="22"/><line x1="22" y1="2" x2="2" y2="22"/></svg>`,
  tunnel: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M 2 12 Q 2 6 6 6 L 18 6 Q 22 6 22 12"/><line x1="2" y1="12" x2="22" y2="12"/></svg>`,
  buffer: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="2" y1="12" x2="22" y2="12"/><line x1="20" y1="8" x2="22" y2="8"/><line x1="20" y1="16" x2="22" y2="16"/></svg>`,
  cabin: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="6" width="16" height="12"/><line x1="12" y1="6" x2="12" y2="18"/></svg>`,
};

export const railwayShapes = [
  {
    id: 'railway-rail',
    label: 'Rail',
    group: 'Railway',
    width: 120,
    height: 40,
    svgIcon: railwaySVGIcons.rail,
    style: { shape: 'customRail', fillColor: 'none', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-signal',
    label: 'Signal',
    group: 'Railway',
    width: 40,
    height: 80,
    svgIcon: railwaySVGIcons.signal,
    style: { shape: 'customSignal', fillColor: 'none', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-switch',
    label: 'Switch',
    group: 'Railway',
    width: 80,
    height: 60,
    svgIcon: railwaySVGIcons.switch,
    style: { shape: 'customSwitch', fillColor: 'none', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-junction',
    label: 'Junction',
    group: 'Railway',
    width: 80,
    height: 80,
    svgIcon: railwaySVGIcons.junction,
    style: { shape: 'customJunction', fillColor: 'none', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-platform',
    label: 'Platform',
    group: 'Railway',
    width: 120,
    height: 50,
    svgIcon: railwaySVGIcons.platform,
    style: { shape: 'customPlatform', fillColor: '#e8f4f9', strokeColor: '#0066cc', strokeWidth: 2 },
  },
  {
    id: 'railway-station',
    label: 'Station',
    group: 'Railway',
    width: 100,
    height: 100,
    svgIcon: railwaySVGIcons.station,
    style: { shape: 'customStation', fillColor: '#fff9e6', strokeColor: '#ff9800', strokeWidth: 2 },
  },
  {
    id: 'railway-crossing',
    label: 'Crossing',
    group: 'Railway',
    width: 80,
    height: 80,
    svgIcon: railwaySVGIcons.crossing,
    style: { shape: 'customCrossing', fillColor: 'none', strokeColor: '#d32f2f', strokeWidth: 3 },
  },
  {
    id: 'railway-tunnel',
    label: 'Tunnel',
    group: 'Railway',
    width: 120,
    height: 70,
    svgIcon: railwaySVGIcons.tunnel,
    style: { shape: 'customTunnel', fillColor: '#c0c0c0', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-buffer',
    label: 'Buffer',
    group: 'Railway',
    width: 80,
    height: 50,
    svgIcon: railwaySVGIcons.buffer,
    style: { shape: 'customBuffer', fillColor: '#f0f0f0', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-cabin',
    label: 'Cabin',
    group: 'Railway',
    width: 90,
    height: 110,
    svgIcon: railwaySVGIcons.cabin,
    style: { shape: 'customCabin', fillColor: '#e3f2fd', strokeColor: '#1976d2', strokeWidth: 2 },
  },

  // Track Circuit Diagram Elements
  {
    id: 'railway-lta',
    label: 'LTA (Track Area)',
    group: 'Track Circuit',
    width: 30,
    height: 40,
    svgIcon: `<svg viewBox="0 0 24 24" fill="currentColor"><polygon points="24,0 24,24 0,12"/></svg>`,
    style: { shape: 'customLTA', fillColor: '#000000', strokeColor: '#000000', strokeWidth: 1 },
  },
  {
    id: 'railway-lto',
    label: 'LTO (Track Output)',
    group: 'Track Circuit',
    width: 30,
    height: 40,
    svgIcon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="0,0 0,24 24,12"/></svg>`,
    style: { shape: 'customLTO', fillColor: 'none', strokeColor: '#000000', strokeWidth: 2 },
  },
  {
    id: 'railway-detection',
    label: 'Detection Point',
    group: 'Track Circuit',
    width: 40,
    height: 40,
    svgIcon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="8"/></svg>`,
    style: { shape: 'customDetectionPoint', fillColor: 'none', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-track-section',
    label: 'Track Section',
    group: 'Track Circuit',
    width: 120,
    height: 20,
    svgIcon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><line x1="0" y1="12" x2="24" y2="12"/></svg>`,
    style: { shape: 'customTrackSection', fillColor: 'none', strokeColor: '#333333', strokeWidth: 3 },
  },
  {
    id: 'railway-vertical-connector',
    label: 'Vertical Connector',
    group: 'Track Circuit',
    width: 20,
    height: 60,
    svgIcon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="0" x2="12" y2="24"/></svg>`,
    style: { shape: 'customVerticalConnector', fillColor: 'none', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-eol-marker',
    label: 'End of Line',
    group: 'Track Circuit',
    width: 40,
    height: 40,
    svgIcon: `<svg viewBox="0 0 24 24" fill="white" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="8"/></svg>`,
    style: { shape: 'customEOLMarker', fillColor: '#ffffff', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-rail-level',
    label: 'Rail Level',
    group: 'Track Circuit',
    width: 100,
    height: 40,
    svgIcon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="0" y1="8" x2="24" y2="8"/><line x1="0" y1="16" x2="24" y2="16"/></svg>`,
    style: { shape: 'customRailLevel', fillColor: 'none', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-sloped-track',
    label: 'Sloped Track',
    group: 'Track Circuit',
    width: 100,
    height: 60,
    svgIcon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="0" y1="8" x2="24" y2="16"/><line x1="0" y1="16" x2="24" y2="8"/></svg>`,
    style: { shape: 'customSlopedTrack', fillColor: 'none', strokeColor: '#333333', strokeWidth: 2 },
  },

  // CBTC/Modern Signaling Elements
  {
    id: 'railway-train',
    label: 'Train',
    group: 'Rolling Stock',
    width: 120,
    height: 60,
    svgIcon: `<svg viewBox="0 0 24 24" fill="currentColor" stroke="black" stroke-width="1"><rect x="4" y="6" width="16" height="10" rx="2"/><circle cx="7" cy="18" r="2"/><circle cx="17" cy="18" r="2"/></svg>`,
    style: { shape: 'customTrain', fillColor: '#8b4513', strokeColor: '#000000', strokeWidth: 2 },
  },
  {
    id: 'railway-signal-head',
    label: 'Signal Head',
    group: 'Signaling',
    width: 50,
    height: 100,
    svgIcon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="6" y="2" width="12" height="12"/><line x1="12" y1="14" x2="12" y2="24"/><circle cx="12" cy="8" r="2" fill="red"/></svg>`,
    style: { shape: 'customSignalHead', fillColor: '#f0f0f0', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-rbc',
    label: 'RBC (Radio Block Center)',
    group: 'Signaling',
    width: 60,
    height: 70,
    svgIcon: `<svg viewBox="0 0 24 24" fill="currentColor" stroke="black" stroke-width="2"><polygon points="12,2 22,22 2,22"/></svg>`,
    style: { shape: 'customRBC', fillColor: '#4169e1', strokeColor: '#000080', strokeWidth: 2 },
  },
  {
    id: 'railway-communication-line',
    label: 'GSM-R Communication',
    group: 'Signaling',
    width: 150,
    height: 15,
    svgIcon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-dasharray="4,4"><line x1="0" y1="6" x2="24" y2="6"/></svg>`,
    style: { shape: 'customCommunicationLine', fillColor: 'none', strokeColor: '#9370db', strokeWidth: 2 },
  },
  {
    id: 'railway-eb-section',
    label: 'Electronic Block (EB)',
    group: 'Track Circuit',
    width: 140,
    height: 40,
    svgIcon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="8" width="20" height="8"/></svg>`,
    style: { shape: 'customEBSection', fillColor: '#e8f4f9', strokeColor: '#0066cc', strokeWidth: 2 },
  },
  {
    id: 'railway-wayside-equipment',
    label: 'Wayside Equipment',
    group: 'Infrastructure',
    width: 50,
    height: 80,
    svgIcon: `<svg viewBox="0 0 24 24" fill="currentColor" stroke="black" stroke-width="1"><rect x="6" y="10" width="12" height="10"/><rect x="10" y="2" width="4" height="8"/><circle cx="12" cy="2" r="1.5" fill="red"/></svg>`,
    style: { shape: 'customWaysideEquipment', fillColor: '#c0c0c0', strokeColor: '#333333', strokeWidth: 2 },
  },
  {
    id: 'railway-track-circuit',
    label: 'Track Circuit',
    group: 'Track Circuit',
    width: 140,
    height: 50,
    svgIcon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="0" y1="6" x2="24" y2="6"/><line x1="0" y1="14" x2="24" y2="14"/><line x1="3" y1="6" x2="3" y2="14"/><line x1="9" y1="6" x2="9" y2="14"/><line x1="15" y1="6" x2="15" y2="14"/><line x1="21" y1="6" x2="21" y2="14"/></svg>`,
    style: { shape: 'customTrackCircuit', fillColor: 'none', strokeColor: '#333333', strokeWidth: 2 },
  },
];
