/**
 * Script to convert arrow SVGs to vertex shape classes
 * Run with: npx ts-node tools/convert-arrows.ts
 */

import { SvgToVertexConverter } from '../src/shapes/svg-to-vertex-converter.js';
import { svgArrows } from '../src/shapes/arrows/svg-arrows.js';

const arrows = [
  { name: 'WideArrow', svg: svgArrows.wideArrow },
  { name: 'ThinArrow', svg: svgArrows.thinArrow },
  { name: 'DoubleArrow', svg: svgArrows.doubleArrow },
  { name: 'NotchedArrow', svg: svgArrows.notchedArrow },
  { name: 'SplitArrow', svg: svgArrows.splitArrow },
  { name: 'CurvedArrow', svg: svgArrows.curvedArrow },
  { name: 'LoopArrow', svg: svgArrows.loopArrow },
  { name: 'ChevronArrow', svg: svgArrows.chevronArrow },
  { name: 'ZigzagArrow', svg: svgArrows.zigzagArrow },
  { name: 'HollowArrow', svg: svgArrows.hollowArrow },
];

console.log('/**\n * Auto-generated arrow shape classes from SVG\n * Generated by convert-arrows.ts\n */\n');
console.log("import { RectangleShape } from '@maxgraph/core';\n");

arrows.forEach(({ name, svg }) => {
  const pathData = SvgToVertexConverter.extractPath(svg);
  if (pathData) {
    const converter = new SvgToVertexConverter(pathData);
    const classCode = converter.generateShapeClass(name + 'Shape');
    console.log(classCode);
    console.log();
  } else {
    console.log(`// WARNING: Could not extract path from ${name}`);
  }
});
