/**
 * @file drawio-importer.ts
 * @brief Import draw.io shape library to railway-drawer format
 * @details
 * Converts draw.io XML library export to railway-drawer shape registry
 *
 * Usage:
 *   npx ts-node tools/drawio-importer.ts path/to/ERTMS.xml
 */

import fs from 'fs';
import path from 'path';
import { DOMParser } from 'xmldom';

interface DrawioShape {
  xml: string;
  w: number;
  h: number;
  aspect: string;
  title: string;
}

function decodeXml(encoded: string): string {
  const decoded = encoded
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');
  return decoded;
}

function extractShapeData(shape: DrawioShape): {
  name: string;
  width: number;
  height: number;
  xml: string;
  svg?: string;
} {
  const xml = decodeXml(shape.xml);

  return {
    name: shape.title,
    width: shape.w,
    height: shape.h,
    xml: xml,
  };
}

function generateShapeRegistration(shapes: DrawioShape[]): string {
  const shapeList = shapes.map((shape, idx) => {
    const data = extractShapeData(shape);
    return `
  {
    id: '${data.name.toLowerCase().replace(/\s+/g, '-')}',
    name: '${data.name}',
    category: 'ERTMS',
    width: ${Math.round(data.width)},
    height: ${Math.round(data.height)},
    // XML: ${data.xml.substring(0, 100)}...
    // Import from draw.io library - ${shape.title}
  }`;
  });

  return `/**
 * ERTMS Shapes imported from draw.io library
 * Generated by drawio-importer.ts
 */

export const ertmsShapes = [
${shapeList.join(',\n')}
];

export const ertmsGroup = {
  name: 'ERTMS',
  title: 'Railway ERTMS',
  description: 'European Railway Traffic Management System shapes',
  shapes: ertmsShapes.map(s => ({
    id: s.id,
    name: s.name,
    category: s.category,
    width: s.width,
    height: s.height,
  })),
};
`;
}

function main() {
  const filePath = process.argv[2];

  if (!filePath) {
    console.error('Usage: npx ts-node tools/drawio-importer.ts <path-to-ERTMS.xml>');
    process.exit(1);
  }

  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    process.exit(1);
  }

  const content = fs.readFileSync(filePath, 'utf-8');

  // Parse JSON array format
  let shapes: DrawioShape[] = [];
  try {
    shapes = JSON.parse(content);
  } catch (e) {
    console.error('Failed to parse ERTMS.xml as JSON');
    process.exit(1);
  }

  console.log(`📦 Found ${shapes.length} shapes in library`);
  console.log('\n📋 Shapes:');
  shapes.forEach((shape, idx) => {
    console.log(`  ${idx + 1}. ${shape.title} (${shape.w}x${shape.h})`);
  });

  const registration = generateShapeRegistration(shapes);

  const outputPath = path.join(path.dirname(filePath), '../railway-drawer/src/shapes/ertms/shapes-config.ts');
  fs.writeFileSync(outputPath, registration);

  console.log(`\n✅ Generated: ${outputPath}`);
  console.log('\n📝 Next steps:');
  console.log('1. Review generated shapes-config.ts');
  console.log('2. Create shape classes in shapes.ts');
  console.log('3. Register shapes in registry.ts');
  console.log('4. Add to index.ts for export');
}

main();
